### ISSUE TITLE
error while building tomahawk

### ISSUE THREAD

**Issue by gordielachance** [tomahawk-player/homebrew-tomahawkqt5#7]
Got this when trying to install tomahawk following this guide : http://wiki.tomahawk-player.org/index.php/Building_OS_X_Application_Bundle

> brew install --HEAD vlc
==> Installing vlc from tomahawk-player/homebrew-tomahawkqt5
==> Cloning git://git.videolan.org/vlc/vlc-2.2.git
Updating /Library/Caches/Homebrew/vlc--git
==> Checking out branch master
Adding libintl directly to the environment:  and ==> export ACLOCAL_ARGS="-I /usr/local/share/aclocal"; export LDFLAGS="-L/usr/lo
xcrun: error: unable to lookup item 'SDKVersion' in SDK '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk'
OSX_VERSION not specified, assuming 
SDKROOT not found at /Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk, trying /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
SDKROOT not found at /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk, trying /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
*** /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk does not exist, please install required SDK, or set SDKROOT manually. ***

**Comment by muesli** [comment]
You seem to be missing xcode and its command line tools.
